### ISSUE TITLE
Crashes when trying to check remote assets

### ISSUE THREAD

**Issue by xvitaly** [hughsie/appstream-glib#454]
Description of problem:
Crashes when trying to check remote assets.

Version-Release number of selected component (if applicable):
`libappstream-glib-0.8.0-1.fc36`

How reproducible:
Always.

Steps to Reproduce:
1. `wget https://xvitaly.fedorapeople.org/bug-reports/org.easycoding.TunedSwitcher.metainfo.xml`
2. `appstream-util validate org.easycoding.TunedSwitcher.metainfo.xml`

Actual results:
```
/home/vitaly/org.easycoding.TunedSwitcher.metainfo.xml: 
(appstream-util:4485): GLib-GIO-CRITICAL **: 16:23:00.242: g_proxy_resolver_lookup: assertion 'G_IS_PROXY_RESOLVER (resolver)' failed
Segmentation fault (core dumped)
```

Expected results:
Successful validation.

Additional info:
```
#0  0x00007ffff7f5e360 in ai_app_validate_image_check (helper=0x5555555d2a80,
    im=0x5555555d3a80) at ../libappstream-glib/as-app-validate.c:476
#1  as_app_validate_image (helper=0x5555555d2a80, im=0x5555555d3a80)
    at ../libappstream-glib/as-app-validate.c:631
#2  as_app_validate_screenshot (helper=0x5555555d2a80, ss=0x5555555b2360)
    at ../libappstream-glib/as-app-validate.c:663
#3  as_app_validate_screenshots (helper=0x5555555d2a80, app=0x5555555db200)
    at ../libappstream-glib/as-app-validate.c:821
#4  as_app_validate (app=app@entry=0x5555555db200, flags=flags@entry=0,
    error=error@entry=0x7fffffffd8b0) at ../libappstream-glib/as-app-validate.c:1627
#5  0x0000555555562ca3 in as_util_validate_file (error=0x7fffffffd8b0,
    flags=AS_APP_VALIDATE_FLAG_NONE,
    filename=0x7fffffffdfbc "org.easycoding.TunedSwitcher.metainfo.xml")
    at ../client/as-util.c:2801
#6  as_util_validate_files (filenames=0x7fffffffdba8, flags=AS_APP_VALIDATE_FLAG_NONE,
    error=0x7fffffffd948) at ../client/as-util.c:2840
#7  0x000055555555d1af in as_util_run (error=0x7fffffffd948, values=<optimized out>,
    command=0x7fffffffdfb3 "validate", priv=0x55555557ffa0) at ../client/as-util.c:170
#8  main (argc=<optimized out>, argv=<optimized out>) at ../client/as-util.c:4755
```

**Comment by hughsie** [comment]
Fixed in https://github.com/hughsie/appstream-glib/pull/450

**Comment by xvitaly** [comment]
@hughsie Can you backport this fix to Fedora package?

**Comment by hughsie** [comment]
I'm about to disappear for PTO, but I can certainly click on a "merge" button.

**Comment by xvitaly** [comment]
@hughsie https://src.fedoraproject.org/rpms/libappstream-glib/pull-request/1

Please build it both for F36 and F37.

**Comment by hughsie** [comment]
Done, teamwork! Thanks.
