### ISSUE TITLE
Crashes on assertion in as_release_set_description()

### ISSUE THREAD

**Issue by ximion** [hughsie/appstream-glib#54]
Hi!
ASGlib crashes on non-null assertion when loading the following valid AppStream XML file:
http://people.freedesktop.org/~mak/stuff/neverball-lirepo/indices/amd64/Metadata.xml.gz

This is highly likely because the file doesn't contain a description for releases.
GDB backtrace:

```
as_release_node_parse (release=release@entry=0x7fffd000c430, node=node@entry=0x7fffd000a390, 
    ctx=ctx@entry=0x7fffd000abb0, error=error@entry=0x7fffe37fd900) at as-release.c:477
477                             as_release_set_description (release,
(gdb) bt full
#0  as_release_node_parse (release=release@entry=0x7fffd000c430, node=node@entry=0x7fffd000a390, 
    ctx=ctx@entry=0x7fffd000abb0, error=error@entry=0x7fffe37fd900) at as-release.c:477
        xml = 0x0
        n = 0x7fffd000a400
        tmp = <optimized out>
        taken = <optimized out>
        i = <optimized out>
#1  0x00007ffff7bb5ec4 in as_app_node_parse_child (error=0x7fffe37fd900, ctx=0x7fffd000abb0, 
    flags=AS_APP_PARSE_FLAG_NONE, n=0x7fffd000a360, app=0xb7eb40) at as-app.c:3709
        r = 0x7fffd000c430
        c = 0x7fffd000a390
        tmp = <optimized out>
        taken = <optimized out>
#2  as_app_node_parse_full (app=app@entry=0xb7eb40, node=node@entry=0x7fffd000a240, 
    flags=flags@entry=AS_APP_PARSE_FLAG_NONE, ctx=ctx@entry=0x7fffd000abb0, error=error@entry=0x7fffe37fd900)
    at as-app.c:3839
        n = 0x7fffd000a360
        tmp = <optimized out>
        prio = <optimized out>
#3  0x00007ffff7bb69ad in as_app_node_parse (app=app@entry=0xb7eb40, node=node@entry=0x7fffd000a240, 
    ctx=ctx@entry=0x7fffd000abb0, error=error@entry=0x7fffe37fd900) at as-app.c:3866
No locals.
#4  0x00007ffff7bc4788 in as_store_from_root (store=store@entry=0x7bb720, root=root@entry=0xbb8320, 
    icon_root=<optimized out>, icon_root@entry=0x7fffd0009df0 "/usr/share/app-info/icons", 
    error=error@entry=0x7fffe37fdba8) at as-store.c:827
        error_local = 0x0
        app = 0xb7eb40
        apps = <optimized out>
        n = 0x7fffd000a240
        tmp = <optimized out>
        ctx = 0x7fffd000abb0
        icon_path = 0x7fffd00169a0 "/usr/share/app-info/icons/6375db4bb7186c39a4860544884575f7"
        __FUNCTION__ = "as_store_from_root"
#5  0x00007ffff7bc4d96 in as_store_from_file (store=store@entry=0x7bb720, file=file@entry=0x8951a0, 
    icon_root=icon_root@entry=0x7fffd0009df0 "/usr/share/app-info/icons", cancellable=cancellable@entry=0x0, 
    error=error@entry=0x7fffe37fdba8) at as-store.c:961
        filename = 0x7fffd0009f70 "/usr/share/app-info/xmls/limba_6375db4bb7186c39a4860544884575f7.xml.gz"
        error_local = 0x0
        root = 0xbb8320
        __FUNCTION__ = "as_store_from_file"
#6  0x00007ffff7bc4f39 in as_store_load_app_info_file (error=0x7fffe37fdba8, cancellable=0x0, 
    icon_root=0x7fffd0009df0 "/usr/share/app-info/icons", 
    path_xml=0x7fffd0009e20 "/usr/share/app-info/xmls/limba_6375db4bb7186c39a4860544884575f7.xml.gz", 
    store=0x7bb720) at as-store.c:1427
        file = 0x8951a0
#7  as_store_load_app_info (store=store@entry=0x7bb720, path=path@entry=0x7fffd0001d50 "/usr/share/app-info", 
    format=format@entry=0x7ffff7bcc23d "xmls", cancellable=cancellable@entry=0x0, error=error@entry=0x7fffe37fdba8)
    at as-store.c:1514
        filename_md = 0x7fffd0009e20 "/usr/share/app-info/xmls/limba_6375db4bb7186c39a4860544884575f7.xml.gz"
        tmp = <optimized out>
        dir = 0x7fffd0001830
        error_local = 0x0
        icon_root = 0x7fffd0009df0 "/usr/share/app-info/icons"
        path_md = 0x7fffd0001d80 "/usr/share/app-info/xmls"
```

**Comment by ximion** [comment]
Awesome, that was quick :-)
Thanks!
